-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Gegenereerd op: 14 dec 2018 om 08:21
-- Serverversie: 5.7.19
-- PHP-versie: 7.1.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `gameworld`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `gamecategory`
--

CREATE TABLE `gamecategory` (
  `categoryId` int(3) NOT NULL,
  `categoryTitle` varchar(50) NOT NULL,
  `categoryDescription` text NOT NULL,
  `categoryImage` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Gegevens worden geëxporteerd voor tabel `gamecategory`
--

INSERT INTO `gamecategory` (`categoryId`, `categoryTitle`, `categoryDescription`, `categoryImage`) VALUES
(1, 'Playstation', '', 'playstation.png'),
(2, 'Xbox', '', 'xbox.jpg'),
(3, 'Pc', '', 'pc.jpg');

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `games`
--

CREATE TABLE `games` (
  `gameId` int(3) NOT NULL COMMENT 'product id is uniek',
  `gameTitle` varchar(50) NOT NULL,
  `gameDescription` text NOT NULL,
  `gamePrice` decimal(5,2) NOT NULL,
  `categoryId` int(11) NOT NULL,
  `gameImage` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Gegevens worden geëxporteerd voor tabel `games`
--

INSERT INTO `games` (`gameId`, `gameTitle`, `gameDescription`, `gamePrice`, `categoryId`, `gameImage`) VALUES
(1, 'Rocket League', 'Voetbal en autorijden worden opnieuw gecombineerd in dit langverwachte, op fysica gebaseerde vervolg van de geliefde arena-klassieker Supersonic Acrobatic Rocket-Powered Battle-Cars!\r\n\r\nHet futuristische sport-actie spel Rocket League® voorziet spelers van voertuigen met boosters waarmee je tegen ballen aan kunt crashen om zo geweldige doelpunten of epische reddingen te maken in verschillende gedetailleerde arena\'s. Met behulp van een geavanceerd fysisch systeem om realistische acties te stimuleren, steunt Rocket League® op massa en momentum om spelers een volledig gevoel van intuïtieve controle te geven in deze ongelooflijke, krachtige geherinterpreteerde manier van verenigingsvoetbal spelen.\r\n', '19.99', 1, 'rocketleague.jpg'),
(2, 'Tom Clancy\'s Rainbow Six Siege', '\r\nBecome a master of vandalism and gadgets in Tom Clancy\'s Rainbow Six Siege. Engage deadly battles in small spaces, make tactical decisions, play in teams and experience banging action. Enter a new era of firefighting and expert strategies stemming from the rich history of previous Tom Clancy\'s Rainbow Six games.', '39.99', 3, 'rainbow.jpg'),
(3, 'Farming Simulator 19', '\r\nmillions of selling franchises make a big leap forward in 2018 - the ultimate farming simulation returns this year with a complete overhaul of the graphics engine, the most striking and immersive images and effects, along with the deepest and most complete farming experience ever.', '34.99', 1, 'farming.jpg'),
(4, 'ARK: Survival Evolved', 'As a man or woman stranded naked, freezing and starving on the shores of a mysterious island called ARK, you must hunt, harvest resources, craft items, grow crops, research technologies, and build shelters to withstand the elements. Use your cunning and resources to kill or tame & breed the leviathan dinosaurs and other primeval creatures roaming the land, and team up with or prey on hundreds of other players to survive, dominate... and escape!\r\n\r\n\r\n\r\nDinosaurs, Creatures, & Breeding! -- over 100+ creatures can be tamed using a challenging capture-&-affinity process, involving weakening a feral creature to knock it unconscious, and then nursing it back to health with appropriate food. Once tamed, you can issue commands to your tames, which it may follow depending on how well you’ve tamed and trained it. Tames, which can continue to level-up and consume food, can also carry Inventory and Equipment such as Armor, carry prey back to your settlement depending on their strength, and larger tames can be ridden and directly controlled! Fly a Pterodactyl over the snow-capped mountains, lift allies over enemy walls, race through the jungle with a pack of Raptors, tromp through an enemy base along a gigantic brontosaurus, or chase down prey on the back of a raging T-Rex! Take part in a dynamic ecosystem life-cycle with its own predator & prey hierarchies, where you are just one creature among many species struggling for dominance and survival. Tames can also be mated with the opposite gender, to selectively breed successive generations using a trait system based on recombinant genetic inheritance. This process includes both egg-based incubation and mammalian gestation lifecycles! Or put more simply, raise babies!\r\n', '54.99', 2, 'ark.jpg'),
(5, ' Counter-Strike: Global Offensive', 'Counter-Strike: Global Offensive (CS: GO) will expand upon the team-based action gameplay that it pioneered when it was launched 14 years ago.\r\n\r\nCS: GO features new maps, characters, and weapons and delivers updated versions of the classic CS content (de_dust2, etc.). In addition, CS: GO will introduce new gameplay modes, matchmaking, leader boards, and more.\r\n\r\n\"Counter-Strike took the gaming industry by surprise when the unlikely MOD became the most played online PC action game in the world almost immediately after its release in August 1999,\" said Doug Lombardi at Valve. \"For the past 12 years, it has continued to be one of the most-played games in the world, headline competitive gaming tournaments and selling over 25 million units worldwide across the franchise. CS: GO promises to expand on CS\' award-winning gameplay and deliver it to gamers on the PC as well as the next gen consoles and the Mac.\"', '12.49', 3, 'csgo.jpg'),
(6, 'Playerunknown\'s Battlegrounds', 'PLAYERUNKNOWN\'S BATTLEGROUNDS is a battle royale shooter that pits 100 players against each other in a struggle for survival. Gather supplies and outwit your opponents to become the last person standing. \r\n\r\nPLAYERUNKNOWN, aka Brendan Greene, is a pioneer of the battle royale genre and the creator of the battle royale game modes in the ARMA series and H1Z1: King of the Kill. At PUBG Corp., Greene is working with a veteran team of developers to make PUBG into the world\'s premiere battle royale experience.', '29.99', 2, 'pubg.jpg'),
(7, 'F1 2018', 'WEES VOORPAGINANIEUWS in F1® 2018.\r\n\r\nF1® 2018 is de officiële videogame van het FIA FORMULA ONE WORLD CHAMPIONSHIP™ 2018. \r\n\r\nWerk zowel op als naast de baan aan je reputatie met tijdsgebonden interviews die invloed hebben op je carrière in de Formule 1. Ga jij voor de sport of de publiciteit? Ontwikkel jij je team naar de top of stuur je je agent af op een rivaliserend team? Met F1 2018 heb jij je lot in eigen handen.\r\no Meer klassieke F1-auto\'s dan ooit\r\no Het nauwkeurigste simulatiemodel van een F1-auto tot nu toe\r\no Prachtige graphics en nieuwe circuits voor 2018: Paul Ricard en Hockenheim', '54.99', 1, 'f1.jpg'),
(8, 'Squad', 'Squad is a large scale combined arms multiplayer first-person shooter emphasizing combat realism through communication, teamplay, emphasizing strong squad cohesion mechanics as well as larger scale coordination, tactics and planning. It features large open maps, vehicle-based combined arms gameplay, and player-constructed bases to create a heart-thumping, visceral gaming experience which mixes organized tactical multi-squad planning with split second decision-making in real-world scale firefights', '36.99', 3, 'Squad.jpg'),
(9, 'Grand Theft Auto V', 'Open samen met de legendarische impresario Tony Prince een nachtclub waar wereldberoemde dj\'s optreden, zoals Solomun, Tale Of Us, Dixon en The Black Madonna. Gebruik de club als dekmantel voor het crimineelste misdaadnetwerk dat San Andreas ooit heeft gezien. \r\n\r\nEen jonge hustler, een gepensioneerde bankrover en een angstaanjagende psychopaat moeten het opnemen tegen de meest gestoorde elementen uit de onderwereld, de Amerikaanse overheid en de entertainment-industrie. Samen moeten ze een reeks gevaarlijke overvallen uitvoeren en zien te overleven in een meedogenloze stad waarin ze niemand kunnen vertrouwen, en elkaar nog het minst.\r\n\r\nIn Grand Theft Auto V voor PC kun je de bekroonde wereld van Los Santos en Blaine County verkennen met een resolutie van 4k of hoger en met wel 60 frames per seconde. \r\n\r\nDe game biedt je enorm veel PC-specifieke aanpassingsopties, waaronder meer dan 25 afzonderlijke instellingen voor textuurkwaliteit, shaders, mozaïeken en anti-aliasing. Ook kun je de besturing met muis en toetsenbord volledig naar wens aanpassen. Verder kun je met een schuifregelaar de verkeersdrukte en het aantal voetgangers bepalen en ondersteunt de game het gebruik van twee of drie schermen. De game is 3D-compatibel en biedt plug-and-play ondersteuning voor controllers. \r\n\r\nGrand Theft Auto V voor PC bevat ook Grand Theft Auto Online, met ondersteuning voor maar liefst 30 spelers en twee toeschouwers. Grand Theft Auto Online voor PC bevat alle bestaande gameplay-upgrades en Rockstar-content die sinds de lancering van Grand Theft Auto Online zijn uitgebracht, inclusief de speltypen Heists en Adversary.\r\n\r\nGrand Theft Auto V en Grand Theft Auto Online voor PC bevatten ook het compleet nieuwe First Person Mode, waarin je de ongelofelijk gedetailleerde wereld van Los Santos en Blaine County op een totaal nieuwe manier kunt verkennen.', '29.99', 2, 'gta.jpg'),
(10, 'Project CARS 2', 'KENMERKEN: \r\n• Meer dan 180 race- en straatauto\'s van hoogstaande merken\r\n• Volledige 12K- en VR-ondersteuning\r\n• Getest en getuned door professionele coureurs en gamers voor levensecht rijgedrag\r\n• Carrièrevoortgang gebaseerd op de echte wereld\r\n• Compleet nieuwe motorsporten (IndyCar, Oval racing, rallycross) plus oude favorieten, waaronder GT3\r\n• Dynamische wegdek- en weereffecten zijn in realtime van invloed op de prestaties en het rijgedrag\r\n• Nieuwe races op onverharde wegen (ijs, losse grond, modder)\r\n• Volledige 24-uurscyclus met realtime sfeervolle en seizoensgebonden omstandigheden\r\n• Toegankelijke gamepadbesturing en ondersteuning voor brede selectie sturen\r\n• eSport-mogelijkheden van topklasse, waaronder Online Championships', '59.99', 1, 'projectcars2.jpg'),
(11, 'Rust', 'The only aim in Rust is to survive.\r\n\r\nTo do this you will need to overcome struggles such as hunger, thirst and cold. Build a fire. Build a shelter. Kill animals for meat. Protect yourself from other players, and kill them for meat. Create alliances with other players and form a town. \r\n\r\nDo whatever it takes to survive.', '29.99', 3, 'rust.jpg'),
(12, 'Dead by Daylight', 'Death Is Not an Escape.\r\n\r\nDead by Daylight is a multiplayer (4vs1) horror game where one player takes on the role of the savage Killer, and the other four players play as Survivors, trying to escape the Killer and avoid being caught, tortured and killed.\r\n\r\nSurvivors play in third-person and have the advantage of better situational awareness. The Killer plays in first-person and is more focused on their prey.\r\n\r\nThe Survivors\' goal in each encounter is to escape the Killing Ground without getting caught by the Killer - something that sounds easier than it is, especially when the environment changes every time you play.\r\n\r\nMore information about the game is available at http://www.deadbydaylight.com', '19.99', 2, 'deadbydaylight.jpg'),
(13, 'For Honor', 'Laat een spoor van vernieling achter in een intens slagveld in For Honor.\r\n\r\n• UNIEKE KRIJGERS OM MEE TE VECHTEN\r\nKies je favoriete krijger uit een verzameling van dappere ridders, bloeddorstige Vikingen en dodelijke samoerai, met elk een eigen wapenset en speelstijl.\r\n\r\n• EEN GEDENKWAARDIG VERHAAL\r\nBestorm kastelen en vestingen, confronteer dodelijke eindbazen en red je mensen van een mysterieuze, dodelijke vijand.\r\n\r\n• VERSLA VIJANDEN IN JE EENTJE OF MET VRIENDEN\r\nFor Honor biedt een spannend offlineverhaal voor één speler en een bloedstollende multiplayer.\r\n\r\n• INNOVATIEF ART-OF-BATTLE-CONTROLESYSTEEM\r\nGebruik het gewicht van je wapen en voel de kracht van elke aanval met dit systeem, waarmee je totale controle over je krijger hebt.\r\n\r\n• VERBREED JOUW ZICHT\r\nKrijg een intensief gevoel voor actie met Tobii Eye Tracking. Kijk rond in wonder, als je blik het scherm schuift en je zicht op het slagveld uitbreidt.\r\nWerkt met alle Tobii Eye Tracking gaming apparaten.\r\n---\r\nExtra notities:\r\nEye tracking functies beschikbaar bij Tobii Eye Tracking.\r\n\r\nOntdek de For Honor VR ervaring: sta in het centrum van de actie met Littlstar.', '14.99', 1, 'forhonor.jpg'),
(14, 'Payday 2', 'PAYDAY 2: VR is now available!\r\nTo activate VR mode please download this free DLC: PAYDAY 2: VR\r\n\r\nPAYDAY 2 is an action-packed, four-player co-op shooter that once again lets gamers don the masks of the original PAYDAY crew - Dallas, Hoxton, Wolf and Chains - as they descend on Washington DC for an epic crime spree. \r\n\r\nThe new CRIMENET network offers a huge range of dynamic contracts, and players are free to choose anything from small-time convenience store hits or kidnappings, to big league cyber-crime or emptying out major bank vaults for that epic PAYDAY. While in DC, why not participate in the local community, and run a few political errands?\r\n\r\nUp to four friends co-operate on the hits, and as the crew progresses the jobs become bigger, better and more rewarding. Along with earning more money and becoming a legendary criminal comes a new character customization and crafting system that lets crews build and customize their own guns and gear.', '9.99', 3, 'payday.jpg'),
(15, 'Just Cause 4', 'Welcome to Solis, a huge South American world home of conflict, oppression and extreme weather conditions. Just Cause 4 sees rogue agent Rico Rodriguez land in Solis to hunt down the truth about his past, at any cost. Strap into your wingsuit, equip your fully customizable grappling hook, and get ready to bring the thunder!\r\n\r\nKEY FEATURES\r\nBring The Thunder:\r\nSoar through the skies with your wingsuit - Skydive, Base Jump and Free Dive with no limits! \r\nFight your enemies under extreme weather conditions, including towering tornadoes and tropical lightning storms, taking the iconic Just Cause action to insane new heights.\r\nUse extreme weather events to your advantage thanks to never seen before in-game physics.\r\n\r\nRico’s Ultimate Mission:\r\nSpearhead the rebellion and defeat the Black Hand, a hi-tech private military organisation.\r\nFace off against Gabriela Morales – your most fierce, capable, and unpredictable adversary yet.\r\nUncover the truth of Rico’s father’s past life on Solis’ and its extreme weather.', '59.99', 2, 'justcause.jpg'),
(16, 'Euro Truck Simulator 2', 'Travel across Europe as king of the road, a trucker who delivers important cargo across impressive distances! With dozens of cities to explore from the UK, Belgium, Germany, Italy, the Netherlands, Poland, and many more, your endurance, skill and speed will all be pushed to their limits. If you’ve got what it takes to be part of an elite trucking force, get behind the wheel and prove it!', '19.99', 3, 'eurotruck.jpg'),
(17, 'BeamNG.drive', 'BeamNG.drive is a realistic, immersive driving game offering near-limitless possibilities. Our soft-body physics engine simulates every component of a vehicle in real time, resulting in realistic, dynamic behavior. \r\nThe driving feel is authentic and visceral, and crashes are realistic and violent; yet the physics are accessible enough to drive with a keyboard or gamepad while still being authentic with a full racing wheel with uncompromising realism.\r\n\r\nEnvironments and vehicles in BeamNG.drive are hand-crafted with passionate attention to detail. With years of meticulous design, research, and experience, we authentically recreate the feeling and excitement of real world driving.\r\n\r\nWe are a small team from around the world with no obligations to publishers or outside interests. Our users and modding community are our first priority. Help us make BeamNG.drive the ultimate driving experience and discover what an open and uncompromising soft-body vehicle simulator can be.', '22.99', 3, 'beamng.jpg'),
(18, 'Outlast 2', 'In Outlast 2 maak je kennis met Sullivan Knoth en zijn volgers, die onze verdorven wereld achter zich hebben gelaten om het stadje Temple Gate te stichten, ergens in de wildernis ver weg van de beschaving. Knoth en zijn volgelingen maken zich klaar voor de beproevingen van de ondergang van de wereld en jij zit er middenin.\r\n\r\nJij bent Blake Langermann, een cameraman die samenwerkt met zijn vrouw Lynn. Samen vormen jullie een team als onderzoeksjournalisten die bereid zijn risico\'s te nemen en diep te graven om verhalen aan het licht te brengen waar niemand anders zich aan durft te wagen.\r\n\r\nJe volgt een spoor van aanwijzingen dat allemaal begonnen is met een ogenschijnlijke onmogelijke moord op een zwangere vrouw die alleen bekend staat als Jane Doe.\r\n\r\nHet onderzoek heeft je mijlendiep de woestijn van Arizona in geleid, naar een overweldigende duisternis waar niemand licht op heeft kunnen werpen. En naar een corruptie zo diepgaand dat gestoord worden de enige logische oplossing lijkt.', '27.99', 3, 'outlast.jpg'),
(19, 'No Man\'s Sky', 'No Man\'s Sky is geïnspireerd op de avonturen en verbeeldingskracht die we van de klassieke sciencefiction kennen en biedt je een heel universum om te verkennen, boordevol unieke planeten, levensvormen, constant gevaar en actie.\r\n\r\nIn No Man\'s Sky is elke ster het licht van een afgelegen zon, elk omringd door bewoonde planeten die je allemaal kunt bezoeken. Vlieg vanuit het diepst van het heelal naar planeetoppervlakken, zonder laadschermen en limieten. In dit oneindige universum ontdek je plekken en wezens die andere spelers nog nooit hebben gezien en misschien ook nooit zullen zien.\r\nGa op een epische reis\r\nIn het centrum van de Melkweg klopt een onweerstaanbaar ritme dat je aanspoort om de ware aard van de kosmos te ontdekken. Geconfronteerd met vijandige wezens en woeste piraten, weet je echter dat je een prijs voor de dood moet betalen en dat overleving volledig aankomt op de keuzes die je maakt voor je schip, wapen en uitrusting.', '54.99', 1, 'nomansky.jpg'),
(20, 'Call of Duty: WWII', 'Bevat Digital Edition Bonuscontent: 1100 Call of Duty-punten**\r\n\r\nCall of Duty® keert terug naar zijn roots met Call of Duty®: WWII , een adembenemende belevenis die een compleet nieuwe draai geeft aan WOII-games voor een nieuwe generatie. Land in Normandië tijdens D-Day en vecht op beroemde locaties door heel Europa in de grootste oorlog uit de geschiedenis. Beleef de klassieke gevechten uit Call of Duty, de kameraadschappen en de keiharde strijd tegen een tirannieke wereldmacht.\r\n\r\nCall of Duty®: WWII is een next-gen-mijlpaal voor games die zich afspelen in de Tweede Wereldoorlog en bestaat uit drie speltypen: Campaign, Multiplayer en Co-Operative. In de visueel adembenemende campagne reis je af naar Europa en beleef je een nieuw verhaal waarin je deelneemt aan de grootste gevechten uit de Tweede Wereldoorlog. De multiplayer grijpt terug naar de oorspronkelijke Call of Duty-gameplay, waarin je met beide laarzen op de grond staat. Authentieke wapens en de klassieke \'run-and-gun\'-actie staan centraal in de gevechten op diverse locaties uit de Tweede Wereldoorlog. In het coöpspeltype beleef je een op zichzelf staand verhaal vol wendingen en bloedstollende momenten.', '59.99', 1, 'ww2.jpg'),
(21, 'Shadow of the Tomb Raider', 'Experience Lara Croft’s defining moment as she becomes the Tomb Raider. In Shadow of the Tomb Raider, Lara must master a deadly jungle, overcome terrifying tombs, and persevere through her darkest hour. As she races to save the world from a Maya apocalypse, Lara will ultimately be forged into the Tomb Raider she is destined to be.\r\n\r\nKEY FEATURES\r\nSurvive and Thrive In the Deadliest Place on Earth: Master an unforgiving jungle setting in order to survive. Explore underwater environments filled with crevasses and deep tunnel systems.\r\nBecome One With the Jungle: Outgunned and outnumbered, Lara must use the jungle to her advantage. Strike suddenly and disappear like a jaguar, use mud as camouflage, and instill fear in enemies to sow chaos.\r\nDiscover Dark and Brutal Tombs: Tombs are more terrifying than ever before, requiring advanced traversal techniques to reach them, and once inside they are filled with deadly puzzles.\r\nUncover Living History: Discover a hidden city and explore the biggest hub space ever found in a Tomb Raider game.', '59.99', 1, 'tombraider.jpeg'),
(22, 'NBA 2K19', 'NBA 2K viert dat we al 20 jaar bepalend zijn in hoe sportgames kunnen zijn, van de beste graphics en gameplay tot vernieuwende speltypen en een enerverende open-world “Neighborhood”. NBA 2K19 legt de lat weer hoger door gaming nog een stap dichter bij de spanning en cultuur van het echte basketbal te brengen.', '49.99', 2, 'k19.jpg'),
(23, 'Far Cry 5', 'Far Cry komt naar Amerika met het nieuwste deel van de bekroonde serie.\r\n\r\nWelkom in Hope County, Montana. Het land van vrijheid en moed, maar ook het thuis van de fanatieke laatste-oordeel-sekte Eden\'s Gate. Sta op tegen sekteleider Joseph Seed en zijn broers, de boodschappers. Wakker het verzet aan en bevrijd de belegerde gemeenschap.\r\n\r\nVECHT TEGEN EEN DODELIJKE SEKTE\r\nBevrijd Hope County alleen of met z\'n tweeën. Rekruteer huurlingen en beesten om de sekte te verslaan.\r\n\r\nEEN WERELD DIE TERUGVECHT\r\nVerwoest de sekte en zijn leden, maar pas op voor de toorn van Joseph Seed en zijn volgelingen.\r\n\r\nVOLG JE EIGEN PAD\r\nStel je personage samen en kies je avontuur in de grootste aanpasbare Far Cry-game ooit!\r\n\r\nDYNAMISCH SPEELGOED\r\nGebruik iconische musclecars, terreinwagens, vliegtuigen en nog veel meer in epische gevechten tegen de sekte.\r\n\r\nGEHERDEFINIEERDE GEHEIME MECHANIEK\r\nVerbeter je gameplay met oogbeweging. Markeer je vijanden door naar hen te kijken om je geheime vaardigheden te verbeteren en je teamgenoten te helpen bedreigingen te signaleren.\r\nCompatibel met alle Tobii Eye Tracking-gamingapparaten. \r\n\r\nAanvullende opmerkingen:\r\noogbewegingsfuncties beschikbaar met Tobii Eye Tracking', '59.99', 2, 'farcry.jpg'),
(24, 'The Crew 2', 'The Crew® 2 is het nieuwste deel van de revolutionaire racereeks. Geniet van Amerikaanse autosport in een van de vetste open werelden ooit. Welkom in Motornation, een gigantisch, gevarieerd, prachtig speelterrein vol actie, gebouwd voor de autosport. Verken de Verenigde Staten te land, ter zee en in de lucht. Rij van kust naar kust, neem deel aan straat- en profraces, verken het terrein, freestyle en strijd in verschillende disciplines. Laat iedereen achter je in razendsnelle wedstrijden en deel elk moment van glorie met de wereld.\r\n\r\nThe Crew® 2 biedt je de kans je kunsten te vertonen en het tot veelzijdig motorsportkampioen te schoppen.\r\n\r\nFEATURES\r\nWELKOM BIJ MOTORNATION – GA DE UITDAGING AAN TE LAND, TER ZEE EN IN DE LUCHT\r\nVerleg grenzen en ga nieuwe uitdagingen aan op spectaculaire locaties. Vlieg en maak tolvluchten door de mist en wolken boven de besneeuwde Rocky Mountains, verbrand rubber in de achterbuurten van New York City, scheur over de Mississippi en verken alle hoeken en gaten van de Grand Canyon. Bestuur de hypercar van je dromen, trap de meest legendarische Amerikaanse motoren op hun staart en kruip achter het stuur van de snelste en meest wendbare vliegtuigen en powerboten. De mogelijkheden voor plezier en uitdaging zijn schier eindeloos in deze volledig herziene versie van de Verenigde Staten.\r\n\r\nWISSEL MOEITELOOS VAN VOERTUIGEN EN GENIET VAN TOTALE VRIJHEID\r\nIn de open wereld van The Crew® 2 draait alles om vrijheid vanachter het stuur van je favoriete voertuigen. De functie Fast Fav stelt je in staat om met één druk op de knop van voertuig te veranderen. Zo kun je het volledige potentieel benutten van deze enorme, naadloze open wereld. Scheur door L.A. in de hypercar van je dromen, schakel over naar een snel en wendbaar vliegtuig waarmee je boven de wolkenkrabbers uittorent en van een adembenemend uitzicht over Hollywood geniet, om vervolgens bij de kustlijn voor een flitsende powerboat en te kiezen vlekkeloos te landen in de Grote Oceaan. De mogelijkheden voor plezier en uitdaging zijn eindeloos.', '59.99', 2, 'crew2.jpg');

--
-- Indexen voor geëxporteerde tabellen
--

--
-- Indexen voor tabel `gamecategory`
--
ALTER TABLE `gamecategory`
  ADD PRIMARY KEY (`categoryId`);

--
-- Indexen voor tabel `games`
--
ALTER TABLE `games`
  ADD PRIMARY KEY (`gameId`);

--
-- AUTO_INCREMENT voor geëxporteerde tabellen
--

--
-- AUTO_INCREMENT voor een tabel `gamecategory`
--
ALTER TABLE `gamecategory`
  MODIFY `categoryId` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT voor een tabel `games`
--
ALTER TABLE `games`
  MODIFY `gameId` int(3) NOT NULL AUTO_INCREMENT COMMENT 'product id is uniek', AUTO_INCREMENT=25;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
